name: pipeline-nexcloud
on: 
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - run: |
          echo "$KEY" > devops.pem
          chmod 400 devops.pem
          scp -o "StrictHostKeyChecking no" -i devops.pem docker-compose.yml ubuntu@$SERVER_IP:.
          ssh -i devops.pem ubuntu@$SERVER-IP "docker-compose up -d"
        env: 
          KEY: $[[secrets.CHAVESSH]]
          SERVER_IP: $[[secrets.IP]]